Start adding some shit

diff --git a/gifme b/gifme
--- a/gifme
+++ b/gifme
@@ -23,6 +23,12 @@
 set -e
 set -o posix
 
+# ffmpeg is a required dependency
+[ ! -z $(which convert) ] || {
+  printf "imagemagick not found. Install it and give it another shot."
+  exit 1;
+}
+
 # Print help/usage with no pattern/args
 test $# -eq 0 -o "$1" = "--help" && {
     cat $0 | grep '^#/' | cut -c4-
@@ -39,7 +45,7 @@ while getopts n opt; do
   esac
 done
 
-cmd='cmd'
+cmd='convert $@ -delay 0 -loop 0 -resize 500 -layers OptimizeTransparency ~/Desktop/animation.gif'
 
 # If we're in test, don't actually run the command
 if $noop
